import Foundation

@MainActor
let gfmRuleSet = RuleSet(
	blocks: [
		indentRule.name: indentRule,
		headingRule.name: headingRule,
		headingUnderlineRule.name: headingUnderlineRule,
		thematicBreakRule.name: thematicBreakRule,
		alertRule.name: alertRule,
		blockQuoteRule.name: blockQuoteRule,
		listOrderedRule.name: listOrderedRule,
		listBulletedRule.name: listBulletedRule,
		listItemRule.name: listItemRule,
		listTaskItemRule.name: listTaskItemRule,
		footnoteReferenceRule.name: footnoteReferenceRule,
		codeBlockRule.name: codeBlockRule,
		codeFenceRule.name: codeFenceRule,
		htmlBlockRule.name: htmlBlockRule,
		linkReferenceRule.name: linkReferenceRule,
		tableRule.name: tableRule,
		paragraphRule.name: paragraphRule,
		contentRule.name: contentRule,
	],
	inlines: [
		autolinkRule.name: autolinkRule,
		extendedAutolinkRule.name: extendedAutolinkRule,
		htmlSpanRule.name: htmlSpanRule,
		codeSpanRule.name: codeSpanRule,
		emphasisRule.name: emphasisRule,
		strikethroughRule.name: strikethroughRule,
		footnoteRule.name: footnoteRule,
		linkRule.name: linkRule,
		hardBreakRule.name: hardBreakRule,
		lineBreakRule.name: lineBreakRule,
		textRule.name: textRule,
	],
	renderers: [
		alertRenderer.name: alertRenderer,
		blockQuoteRenderer.name: blockQuoteRenderer,
		codeBlockRenderer.name: codeBlockRenderer,
		codeFenceRenderer.name: codeFenceRenderer,
		codeSpanRenderer.name: codeSpanRenderer,
		deletionRenderer.name: deletionRenderer,
		emphasisRenderer.name: emphasisRenderer,
		footnoteRenderer.name: footnoteRenderer,
		hardBreakRenderer.name: hardBreakRenderer,
		headingRenderer.name: headingRenderer,
		headingUnderlineRenderer.name: headingUnderlineRenderer,
		htmlBlockRenderer.name: htmlBlockRenderer,
		htmlSpanRenderer.name: htmlSpanRenderer,
		imageRenderer.name: imageRenderer,
		insertionRenderer.name: insertionRenderer,
		linkRenderer.name: linkRenderer,
		listBulletedRenderer.name: listBulletedRenderer,
		listOrderedRenderer.name: listOrderedRenderer,
		listTaskItemRenderer.name: listTaskItemRenderer,
		paragraphRenderer.name: paragraphRenderer,
		strikethroughRenderer.name: strikethroughRenderer,
		strongRenderer.name: strongRenderer,
		subscriptRenderer.name: subscriptRenderer,
		superscriptRenderer.name: superscriptRenderer,
		tableRenderer.name: tableRenderer,
		tableCellRenderer.name: tableCellRenderer,
		tableHeaderRenderer.name: tableHeaderRenderer,
		tableRowRenderer.name: tableRowRenderer,
		textRenderer.name: textRenderer,
		thematicBreakRenderer.name: thematicBreakRenderer,
	]
)
