catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.2.2
  vitest: ^4.1.9
onlyBuiltDependencies:
  - cmark-gfm
  - esbuild
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
